on: push

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            db:
                image: postgres:11
                ports:
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Check out source
              uses: actions/checkout@v3

            - name: Set up Elixir
              id: beam
              uses: erlef/setup-beam@v1
              with:
                otp-version: "25.2"
                elixir-version: "1.14.4"

            - name: Install dependencies
              run: mix deps.get

            - name: Format code
              run: mix format --check-formatted

            - name: Check warnings
              run: mix compile --warnings-as-errors

            - name: Run credo
              run: mix credo
                
            - name: run tests
              run: mix test