on: push

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            db:
                image: postgres:11
                ports:
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Check out source
              uses: actions/checkout@v3

            - name: Set up Elixir
              id: beam
              uses: erlef/setup-beam@v1
              with:
                otp-version: "25.2"
                elixir-version: "1.14.4"

            - name: Install dependencies
              run: mix deps.get

            - name: Format code
              run: mix format --check-formatted

            - name: Check warnings
              run: mix compile --warnings-as-errors

            - name: Run credo
              run: mix credo

            - name: Restore PLT cache
              id: plt_cache
              uses: actions/cache/restore@v3
              with:
                key: |
                  plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
                restore-keys: |
                  plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
                path: |
                  priv/plts

            - name: Create PLTs
              if: steps.plt_cache.outputs.cache-hit != 'true'
              run: mix dialyzer --plt

            - name: Save PLT cache
              id: plt_cache_save
              uses: actions/cache/save@v3
              if: steps.plt_cache.outputs.cache-hit != 'true'
              with:
                key: |
                  plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
                path: |
                  priv/plts

            - name: Run dialyzer
              run: mix dialyzer --format github --format dialyxir
                
            - name: run tests
              run: mix test